{
    "name": "Crispr-form-test",
    "version": "14.0.0.0.1",
    "category": "form view",
    "author": "Article714",
    "license": "LGPL-3",
    "website": "https://www.article714.org",
    "summary": """ """,
    "depends": ["crispr_form"],
    "data": ["views/res_partner_views.xml"],
    "qweb": [],
    "installable": True,
    "images": [],
    "application": False,
}
