stages:
  - docker
  - test

docker-ci-build:
  stage: docker
  tags:
    - shell
  variables:
    BUILD_OPTS: "--network=internal_bridge --force-rm --no-cache --build-arg CI_JOB_TOKEN=${CI_JOB_TOKEN} --build-arg CI_COMMIT_REF_NAME=${CI_COMMIT_REF_NAME}"
  script:
    - cd ci/Docker
    - docker build ${BUILD_OPTS} crispr_form_odoo_ci -t crispr_form_odoo_ci:$CI_PIPELINE_ID

integration-tests:
  stage: test
  tags:
    - docker
  image:
    name: crispr_form_odoo_ci:$CI_PIPELINE_ID
  variables:
    POSTGRES_DB: crispr
    POSTGRES_USER: odoo
    POSTGRES_PASSWORD: odoo
    POSTGRES_HOST_AUTH_METHOD: trust
    PYTEST_PLUGINS: "odoo"
  services:
    - name: article714/postgresql-container:11-latest
      alias: db_postgresql
  script:
    - odoo --logfile=ci/odoo_build.log --stop-after-init --without-demo=all --database=crispr -c $ODOO_RC -i base,web,crispr_form_test
    - cd /home/odoo/addons/crispr-form/modules
    - pytest
  artifacts:
    paths:
      - ci/odoo_build.log
    expire_in: 3 days
    when: always
