{
    "name": "Crispr-form",
    "version": "12.0.0.0.1",
    "category": "form view",
    "author": "Article714",
    "license": "LGPL-3",
    "website": "https://www.article714.org",
    "summary": """ """,
    "depends": [],
    "data": [],
    "qweb": [],
    "installable": True,
    "images": [],
    "application": False,
}
